### ISSUE TITLE
[Bug] Command Serve Panic!

### ISSUE THREAD

**Issue by isoldmysoull** [iyear/tdl#518]
### Describe the bug

Command Used:
```sh
tdl dl -f ExportedChat.json --serve --port 6969
```

### To Reproduce

...

### Expected behavior

...

### Version

v0.16.0

### Which OS are you running tdl on?

Windows

### Additional context

logs

```sh
(Beta) Serving on http://localhost:6969
2024/02/26 04:10:26 http: panic serving [::1]:57268: interface conversion: interface {} is nil, not *zap.Logger
goroutine 57 [running]:
net/http.(*conn).serve.func1()
        net/http/server.go:1868 +0xb9
panic({0x1a797c0?, 0xc000687c50?})
        runtime/panic.go:920 +0x270
github.com/iyear/tdl/pkg/logger.From(...)
        github.com/iyear/tdl/pkg/logger/logger.go:14
github.com/iyear/tdl/pkg/recovery.(*recovery).Handle.func1({0x1fdd898, 0xc000234780}, {0x1fd1ca0?, 0xc000687c20}, {0x1fd1cc0?, 0xc000052600})
        github.com/iyear/tdl/pkg/recovery/recovery.go:32 +0x189
github.com/gotd/td/telegram.InvokeFunc.Invoke(0x30?, {0x1fdd898?, 0xc000234780?}, {0x1fd1ca0?, 0xc000687c20?}, {0x1fd1cc0?, 0xc000052600?})
        github.com/gotd/td@v0.97.0/telegram/middleware.go:15 +0x47
github.com/gotd/td/tg.(*Client).UploadGetFile(0xc000052510, {0x1fdd898, 0xc000234780}, 0x2ccfa8c?)
        github.com/gotd/td@v0.97.0/tg/tl_upload_get_file_gen.go:341 +0x70
github.com/gotd/contrib/tg_io.chunkSource.Chunk({{0x1fed938?, 0xc0000a5340?}, 0xc000052510?, 0x0?}, {0x1fdd898, 0xc000234780}, 0x0, {0xc0006e4000, 0x80000, 0x80000})
        github.com/gotd/contrib@v0.19.0/tg_io/download.go:51 +0xd2
github.com/gotd/contrib/partio.Streamer.safeRead({0x1fdd898?, {0x1fd0c20?, 0xc0006843e0?}}, {0x1fdd898?, 0xc000234780?}, 0xc16f1aa49e677dd4?, {0xc0006e4000?, 0x80000, 0x10e7dd855?})
        github.com/gotd/contrib@v0.19.0/partio/streamer.go:37 +0x54
github.com/gotd/contrib/partio.Streamer.StreamAt({0x0?, {0x1fd0c20?, 0xc0006843e0?}}, {0x1fdd898, 0xc000234780}, 0x0, {0x1fd8800, 0xc0001ca2a0})
        github.com/gotd/contrib@v0.19.0/partio/streamer.go:122 +0x157
github.com/gotd/contrib/http_io.Handler.ServeHTTP({0xc0001f5110, 0x1183f051, {0xc000443c70, 0x9}, {0x1fd0bc0, 0xc0006d2438}}, {0x1fdceb0, 0xc0001ca2a0}, 0xc000356700)
        github.com/gotd/contrib@v0.19.0/http_io/io.go:87 +0x7d0
github.com/iyear/tdl/app/dl.serve.func1({0x1fdceb0, 0xc0001ca2a0}, 0xc000234750?)
        github.com/iyear/tdl/app/dl/serve.go:99 +0x88e
github.com/iyear/tdl/app/dl.serve.handler.func4({0x1fdceb0, 0xc0001ca2a0}, 0xc000234780?)
        github.com/iyear/tdl/app/dl/serve.go:140 +0x22
net/http.HandlerFunc.ServeHTTP(0xc000356600?, {0x1fdceb0?, 0xc0001ca2a0?}, 0x23b76894d40?)
        net/http/server.go:2136 +0x29
github.com/gorilla/mux.(*Router).ServeHTTP(0xc000240000, {0x1fdceb0, 0xc0001ca2a0}, 0xc000356500)
        github.com/gorilla/mux@v1.8.1/mux.go:212 +0x1c5
net/http.serverHandler.ServeHTTP({0xc0002344b0?}, {0x1fdceb0?, 0xc0001ca2a0?}, 0x6?)
        net/http/server.go:2938 +0x8e
net/http.(*conn).serve(0xc0001683f0, {0x1fdd898, 0xc000453650})
        net/http/server.go:2009 +0x5f4
created by net/http.(*Server).Serve in goroutine 12
        net/http/server.go:3086 +0x5cb
2024/02/26 04:10:26 http: panic serving [::1]:57272: interface conversion: interface {} is nil, not *zap.Logger
goroutine 131 [running]:
net/http.(*conn).serve.func1()
        net/http/server.go:1868 +0xb9
panic({0x1a797c0?, 0xc000687f50?})
        runtime/panic.go:920 +0x270
github.com/iyear/tdl/pkg/logger.From(...)
        github.com/iyear/tdl/pkg/logger/logger.go:14
github.com/iyear/tdl/pkg/recovery.(*recovery).Handle.func1({0x1fdd898, 0xc000687e90}, {0x1fd1ca0?, 0xc000687f20}, {0x1fd1cc0?, 0xc000052a80})
        github.com/iyear/tdl/pkg/recovery/recovery.go:32 +0x189
github.com/gotd/td/telegram.InvokeFunc.Invoke(0x30?, {0x1fdd898?, 0xc000687e90?}, {0x1fd1ca0?, 0xc000687f20?}, {0x1fd1cc0?, 0xc000052a80?})
        github.com/gotd/td@v0.97.0/telegram/middleware.go:15 +0x47
github.com/gotd/td/tg.(*Client).UploadGetFile(0xc000052920, {0x1fdd898, 0xc000687e90}, 0x2ccfa8c?)
        github.com/gotd/td@v0.97.0/tg/tl_upload_get_file_gen.go:341 +0x70
github.com/gotd/contrib/tg_io.chunkSource.Chunk({{0x1fed938?, 0xc0000a5340?}, 0xc000052920?, 0x0?}, {0x1fdd898, 0xc000687e90}, 0x0, {0xc000804000, 0x80000, 0x80000})
        github.com/gotd/contrib@v0.19.0/tg_io/download.go:51 +0xd2
github.com/gotd/contrib/partio.Streamer.safeRead({0x1fdd898?, {0x1fd0c20?, 0xc000684440?}}, {0x1fdd898?, 0xc000687e90?}, 0xc16f1aa49e95a2b8?, {0xc000804000?, 0x80000, 0x10eabfd39?})
        github.com/gotd/contrib@v0.19.0/partio/streamer.go:37 +0x54
github.com/gotd/contrib/partio.Streamer.StreamAt({0x0?, {0x1fd0c20?, 0xc000684440?}}, {0x1fdd898, 0xc000687e90}, 0x0, {0x1fd8800, 0xc000468380})
        github.com/gotd/contrib@v0.19.0/partio/streamer.go:122 +0x157
github.com/gotd/contrib/http_io.Handler.ServeHTTP({0xc0001f51f0, 0x1183f051, {0xc000443c70, 0x9}, {0x1fd0bc0, 0xc0006d2480}}, {0x1fdceb0, 0xc000468380}, 0xc0006e2300)
        github.com/gotd/contrib@v0.19.0/http_io/io.go:87 +0x7d0
github.com/iyear/tdl/app/dl.serve.func1({0x1fdceb0, 0xc000468380}, 0xc000687e60?)
        github.com/iyear/tdl/app/dl/serve.go:99 +0x88e
github.com/iyear/tdl/app/dl.serve.handler.func4({0x1fdceb0, 0xc000468380}, 0xc000687e90?)
        github.com/iyear/tdl/app/dl/serve.go:140 +0x22
net/http.HandlerFunc.ServeHTTP(0xc0006e2200?, {0x1fdceb0?, 0xc000468380?}, 0x23b76894d40?)
        net/http/server.go:2136 +0x29
github.com/gorilla/mux.(*Router).ServeHTTP(0xc000240000, {0x1fdceb0, 0xc000468380}, 0xc0006e2100)
        github.com/gorilla/mux@v1.8.1/mux.go:212 +0x1c5
net/http.serverHandler.ServeHTTP({0xc000687cb0?}, {0x1fdceb0?, 0xc000468380?}, 0x6?)
        net/http/server.go:2938 +0x8e
net/http.(*conn).serve(0xc0001c86c0, {0x1fdd898, 0xc000453650})
        net/http/server.go:2009 +0x5f4
created by net/http.(*Server).Serve in goroutine 12
        net/http/server.go:3086 +0x5cb
```

**Comment by bolavefasfas** [comment]
Can we serve a complete channel/ group like this I didnt knew 

I thought serve was only ment to serve a single file 

@isoldmysoull Try serving a single file

**Comment by isoldmysoull** [comment]
@bolavefasfas 
I've cloned and made a modification to the [function](https://github.com/iyear/tdl/blob/e976a27a3937e27c4b8a6700a3f638d50b26420a/pkg/logger/logger.go#L13C6-L13C10), ensuring it returns a new logger instance if the logger was not registered before. compiled, it works fine with IDM.

**Comment by bolavefasfas** [comment]
> @bolavefasfas I've cloned and made a modification to the [function](https://github.com/iyear/tdl/blob/e976a27a3937e27c4b8a6700a3f638d50b26420a/pkg/logger/logger.go#L13C6-L13C10), ensuring it returns a new logger instance if the logger was not registered before. compiled, it works fine with IDM.

![image](https://github.com/iyear/tdl/assets/82230241/66711638-ae7f-4ccd-8544-527507dfc59f)
Message id's show up and when I click on the any message 
![image](https://github.com/iyear/tdl/assets/82230241/10bd4ccd-4fae-435b-9b01-d79fb77d2fac)

and this is in the logs 
```
2024/02/28 05:57:49 http: panic serving 100.100.100.1:51237: interface conversion: interface {} is nil, not *zap.Logger
goroutine 89 [running]:
net/http.(*conn).serve.func1()
        net/http/server.go:1850 +0xb8
panic({0xf9fda0, 0x400035cab0})
        runtime/panic.go:890 +0x260
github.com/iyear/tdl/pkg/logger.From(...)
        github.com/iyear/tdl/pkg/logger/logger.go:14
github.com/iyear/tdl/pkg/recovery.(*recovery).Handle.func1({0x150a700, 0x400035c8d0}, {0x1503ba0, 0x400035ca50}, {0x1503b20, 0x4000454140})
        github.com/iyear/tdl/pkg/recovery/recovery.go:32 +0x138
github.com/gotd/td/telegram.InvokeFunc.Invoke(0x4000580000?, {0x150a700?, 0x400035c8d0?}, {0x1503ba0?, 0x400035ca50?}, {0x1503b20?, 0x4000454140?})
        github.com/gotd/td@v0.89.0/telegram/middleware.go:15 +0x54
github.com/gotd/td/tg.(*Client).UploadGetFile(0x4000454050, {0x150a700, 0x400035c8d0}, 0x9e70c?)
        github.com/gotd/td@v0.89.0/tg/tl_upload_get_file_gen.go:340 +0x78
github.com/gotd/contrib/tg_io.chunkSource.Chunk({{0x1511bd8?, 0x40004c38c0?}, 0x4000454050?, 0x0?}, {0x150a700, 0x400035c8d0}, 0x0, {0x4000800000, 0x80000, 0x40005f3300?})
        github.com/gotd/contrib@v0.19.0/tg_io/download.go:51 +0xc8
github.com/gotd/contrib/partio.Streamer.safeRead({0x150a700?, {0x14fd940?, 0x400012e360?}}, {0x150a700?, 0x400035c8d0?}, 0x0?, {0x4000800000?, 0x80000, 0xc16fd0b75f51cb6c?})
        github.com/gotd/contrib@v0.19.0/partio/streamer.go:37 +0x54
github.com/gotd/contrib/partio.Streamer.StreamAt({0x0?, {0x14fd940?, 0x400012e360?}}, {0x150a700, 0x400035c8d0}, 0x0, {0x1504620, 0x40002580e0})
        github.com/gotd/contrib@v0.19.0/partio/streamer.go:122 +0xe8
github.com/gotd/contrib/http_io.Handler.ServeHTTP({0x400030e2a0, 0x44370021, {0x400065c400, 0xf}, {0x14fd920, 0x400019c018}}, {0x1509c38, 0x40002580e0}, 0x40001fc200)
        github.com/gotd/contrib@v0.19.0/http_io/io.go:87 +0x61c
github.com/iyear/tdl/app/dl.serve.func1({0x1509c38, 0x40002580e0}, 0x150a700?)
        github.com/iyear/tdl/app/dl/serve.go:99 +0x6cc
github.com/iyear/tdl/app/dl.handler.func1({0x1509c38, 0x40002580e0}, 0x4000662110?)
        github.com/iyear/tdl/app/dl/serve.go:140 +0x2c
net/http.HandlerFunc.ServeHTTP(0x40001fc100?, {0x1509c38?, 0x40002580e0?}, 0x800?)
        net/http/server.go:2109 +0x38
github.com/gorilla/mux.(*Router).ServeHTTP(0x40000b2300, {0x1509c38, 0x40002580e0}, 0x40001fc000)
        github.com/gorilla/mux@v1.8.1/mux.go:212 +0x1a4
net/http.serverHandler.ServeHTTP({0x400035c540?}, {0x1509c38, 0x40002580e0}, 0x40001fc000)
        net/http/server.go:2947 +0x2cc
net/http.(*conn).serve(0x4000506320, {0x150a700, 0x4000643410})
        net/http/server.go:1991 +0x544
created by net/http.(*Server).Serve
        net/http/server.go:3102 +0x43c
```

And I updated before running it again using `curl -sSL https://docs.iyear.me/tdl/install.sh | sudo bash`

What am I missing?

**Comment by bolavefasfas** [comment]
@iyear 
![image](https://github.com/iyear/tdl/assets/82230241/746d5672-0354-4bf4-abe1-77bb98c1b6dc)
This gets stuck after downloding 10-20 files then If i give it a cooldown for about an hour or more it starts downloading same file.
