### ISSUE TITLE
got error callback: rpcDoRequest: msg_id too high

### ISSUE THREAD

**Issue by Unintendedz** [iyear/tdl#59]
![image](https://user-images.githubusercontent.com/64687143/203544732-dcb24eaf-3e38-42e7-ba6a-57d364599f58.png)

Hi, I got this error, any tips?

**Comment by Unintendedz** [comment]
Hi, Thank you for your response. After synchronizing my system clock, I got this error

```
panic: runtime error: index out of range [0] with length 0

goroutine 15 [running]:
github.com/iyear/tdl/app/dl.(*iter).Next(0xc000150840, {0x1d28a10?, 0xc0000b85c0?})
        github.com/iyear/tdl/app/dl/iter.go:71 +0xba
github.com/iyear/tdl/pkg/downloader.(*Downloader).Download(0xc000150880, {0x1d28a10, 0xc0000b85c0}, 0x1aec569?)
        github.com/iyear/tdl/pkg/downloader/downloader.go:56 +0x291
github.com/iyear/tdl/app/dl.Run.func1({0x1d28a10, 0xc0000b85c0})
        github.com/iyear/tdl/app/dl/dl.go:33 +0x31d
github.com/iyear/tdl/app/internal/tgc.RunWithAuth.func1({0x1d28a10, 0xc0000b85c0})
        github.com/iyear/tdl/app/internal/tgc/run.go:19 +0xb6
github.com/gotd/td/telegram.(*Client).Run.func3({0x1d28a10, 0xc0000b85c0})
        github.com/gotd/td@v0.69.1/telegram/connect.go:150 +0xe9
github.com/gotd/td/internal/tdsync.(*CancellableGroup).Go.func1()
        github.com/gotd/td@v0.69.1/internal/tdsync/cancel_group.go:48 +0x29
golang.org/x/sync/errgroup.(*Group).Go.func1()
        golang.org/x/sync@v0.0.0-20220819030929-7fc1605a5dde/errgroup/errgroup.go:75 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
        golang.org/x/sync@v0.0.0-20220819030929-7fc1605a5dde/errgroup/errgroup.go:72 +0xa5
```

**Comment by iyear** [comment]
Command format error. `.\tdl.exe -n mytg dl -u https://...`

**Comment by Unintendedz** [comment]
My mistake, Now it works like a charm! Thanks again!
