### ISSUE TITLE
Panic when login

### ISSUE THREAD

**Issue by 1panpan1** [iyear/tdl#65]
panic message:
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0xec3445]

goroutine 1 [running]:
github.com/iyear/tdl/pkg/storage.(*Session).StoreSession(0xc0005889f0, {0xc0005a4000?, 0x13fa7ca?}, {0xc0005b8000, 0xe00, 0x1000})
        github.com/iyear/tdl/pkg/storage/session.go:36 +0x65
github.com/gotd/td/session.(*Loader).Save(0xc0006bf9a0, {0x165c768, 0xc000477540}, 0xc000020180?)
        github.com/gotd/td@v0.69.1/session/session.go:161 +0x12d
github.com/iyear/tdl/app/login.Desktop({0x165c768, 0xc000477540}, {0xc00003c120, 0x16}, {0x0, 0x0})
        github.com/iyear/tdl/app/login/desktop.go:74 +0x619
github.com/iyear/tdl/cmd/login.glob..func1(0x21651e0, {0x13a731d?, 0x2?, 0x2?})
        github.com/iyear/tdl/cmd/login/login.go:21 +0x73
github.com/spf13/cobra.(*Command).execute(0x21651e0, {0xc0004fb8c0, 0x2, 0x2})
        github.com/spf13/cobra@v1.5.0/command.go:872 +0x694
github.com/spf13/cobra.(*Command).ExecuteC(0x2164060)
        github.com/spf13/cobra@v1.5.0/command.go:990 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.5.0/command.go:918
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        github.com/spf13/cobra@v1.5.0/command.go:911
github.com/iyear/tdl/cmd.Execute()
        github.com/iyear/tdl/cmd/root.go:71 +0xf7
main.main()
        github.com/iyear/tdl/main.go:9 +0x19

**Comment by iyear** [comment]
Could you provide more info? Thanks.
